#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Tests example prompt generation and validation for a single tool or family

.DESCRIPTION
    Generates and validates example prompts for a single Azure MCP tool or tool family.
    Useful for quick testing and debugging of the prompt generation pipeline.
    
    Steps:
    1. Filters cli-output.json to include only the specified tool
    2. Generates example prompts for that tool using ExamplePromptGeneratorStandalone
    3. Validates the generated prompts using ExamplePromptValidator
    4. Shows all output files (input prompt, raw output, example prompts, validation)

.PARAMETER ToolCommand
    The tool command to test (e.g., "keyvault secret create", "storage account list")
    Can also be a tool family/namespace prefix to generate all tools in that family (e.g., "keyvault", "storage")

.PARAMETER OutputPath
    Path to the generated directory (default: ../generated from docs-generation root)

.PARAMETER SkipValidation
    Skip the validation step (only generate prompts)

.EXAMPLE
    ./2-Generate-ExamplePrompts-One.ps1 -ToolCommand "keyvault secret create"  # Single tool
    ./2-Generate-ExamplePrompts-One.ps1 -ToolCommand "storage"                      # All storage tools
    ./2-Generate-ExamplePrompts-One.ps1 -ToolCommand "acr registry list" -SkipValidation
#>

param(
    [Parameter(Mandatory=$true)]
    [string]$ToolCommand,
    
    [string]$OutputPath = "../../generated",
    
    [switch]$SkipValidation,

    [switch]$SkipBuild
)

$ErrorActionPreference = "Stop"

# Import shared logging and normalization helpers
. "$PSScriptRoot\Shared-Functions.ps1"

try {
    Write-Divider
    Write-Progress "Single Tool Prompt Generation & Validation Test"
    Write-Info "Tool: $ToolCommand"
    Write-Info "Started: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
    Write-Divider
    Write-Host ""

    $scriptDir = $PSScriptRoot
    $docsGenDir = Split-Path -Parent $scriptDir
    $outputDir = Resolve-OutputDir $OutputPath

    Write-Info "Output directory: $outputDir"
    Write-Host ""

    # Get CLI version
    $cliVersion = Get-CliVersion $outputDir
    Write-Info "CLI Version: $cliVersion"
    Write-Host ""

    # Load full CLI output
    $cli = Get-CliOutput $outputDir

    # Normalize and find matching tools
    $ToolCommand = Normalize-ToolCommand $ToolCommand
    $matchingTools = Find-MatchingTools $cli.AllTools $ToolCommand
    Write-Host ""

    # Create filtered CLI file in temp directory
    $temp = New-FilteredCliFile $cli.CliOutput $matchingTools
    $tempDir = $temp.TempDir
    $filteredOutputFile = $temp.FilteredFile
    Write-Host ""

    # Build .NET packages (skip if already built by preflight)
    Invoke-DotnetBuild -SkipBuild:$SkipBuild

    # Run ExamplePromptGeneratorStandalone
    Write-Divider
    Write-Progress "Generating example prompts..."
    Write-Divider
    Write-Host ""
    
    $generatorProject = Join-Path $docsGenDir "ExamplePromptGeneratorStandalone"
    $noBuildArg = if ($SkipBuild) { "--no-build" } else { "" }

    # Pass e2e reference prompts if available (generated by preflight)
    $e2ePromptsFile = Join-Path $outputDir "e2e-test-prompts/parsed.json"
    $e2eArgs = @()
    if (Test-Path $e2ePromptsFile) {
        $e2eArgs = @("--e2e-prompts", $e2ePromptsFile)
        Write-Info "Using e2e reference prompts: $e2ePromptsFile"
    } else {
        Write-Warning "No e2e reference prompts found at: $e2ePromptsFile (using default prompt count)"
    }

    & dotnet run --project $generatorProject --configuration Release $noBuildArg -- $filteredOutputFile $outputDir $cliVersion @e2eArgs
    
    if ($LASTEXITCODE -ne 0) {
        throw "Example prompts generation failed"
    }

    Write-Host ""
    Write-Divider

    # Show generated files
    if ($matchingTools.Count -eq 1) {
        $singleToolCommand = $matchingTools[0].command
        $baseFileName = Get-ToolBaseFileName $singleToolCommand
        
        $inputPromptFile = Join-Path $outputDir "example-prompts-prompts/$baseFileName-input-prompt.md"
        $rawOutputFile = Join-Path $outputDir "example-prompts-raw-output/$baseFileName-raw-output.txt"
        $examplePromptsFile = Join-Path $outputDir "example-prompts/$baseFileName-example-prompts.md"
    }
    
    Write-Progress "Generated Files:"
    Write-Host ""
    
    if ($matchingTools.Count -eq 1) {
        if (Test-Path $inputPromptFile) {
            Write-Success "✓ Input prompt: $inputPromptFile"
        } else {
            Write-Warning "✗ Input prompt not found: $inputPromptFile"
        }
        
        if (Test-Path $rawOutputFile) {
            Write-Success "✓ Raw AI output: $rawOutputFile"
            Write-Info "  Showing first 20 lines:"
            Get-Content $rawOutputFile | Select-Object -First 20 | ForEach-Object { Write-Host "    $_" -ForegroundColor DarkGray }
            $lineCount = (Get-Content $rawOutputFile).Count
            if ($lineCount -gt 20) {
                Write-Info "    ... ($($lineCount - 20) more lines)"
            }
        } else {
            Write-Warning "✗ Raw output not found: $rawOutputFile"
        }
        
        Write-Host ""
        
        if (Test-Path $examplePromptsFile) {
            Write-Success "✓ Example prompts: $examplePromptsFile"
            Write-Info "  Content:"
            Get-Content $examplePromptsFile | ForEach-Object { Write-Host "    $_" -ForegroundColor DarkGray }
        } else {
            Write-Warning "✗ Example prompts not found: $examplePromptsFile"
        }
    } else {
        $inputDir = Join-Path $outputDir "example-prompts-prompts"
        $rawDir = Join-Path $outputDir "example-prompts-raw-output"
        $promptsDir = Join-Path $outputDir "example-prompts"
        
        $inputCount = if (Test-Path $inputDir) { (Get-ChildItem $inputDir -Filter "*.md" | Measure-Object).Count } else { 0 }
        $rawCount = if (Test-Path $rawDir) { (Get-ChildItem $rawDir -Filter "*.txt" | Measure-Object).Count } else { 0 }
        $promptCount = if (Test-Path $promptsDir) { (Get-ChildItem $promptsDir -Filter "*.md" | Measure-Object).Count } else { 0 }
        
        Write-Success "✓ Input prompts: $inputCount files in $inputDir"
        Write-Success "✓ Raw outputs: $rawCount files in $rawDir"
        Write-Success "✓ Example prompts: $promptCount files in $promptsDir"
    }
    
    Write-Host ""

    # Run validation if not skipped
    if (-not $SkipValidation) {
        Write-Divider
        Write-Progress "Validating example prompts..."
        Write-Divider
        Write-Host ""
        
        if ($matchingTools.Count -eq 1) {
            $validatorScript = Join-Path $docsGenDir "ExamplePromptValidator/scripts/Validate-ExamplePrompts-RequiredParams.ps1"
            & $validatorScript -OutputPath $OutputPath -ToolCommand $singleToolCommand
            
            if ($LASTEXITCODE -ne 0) {
                Write-Warning "Validation completed with issues"
            } else {
                Write-Success "✓ Validation completed successfully"
            }
            
            Write-Host ""
            
            # Show validation file
            $validationFile = Join-Path $outputDir "example-prompts-validation/$baseFileName-validation.md"
            if (Test-Path $validationFile) {
                Write-Success "✓ Validation report: $validationFile"
                Write-Info "  Content:"
                Get-Content $validationFile | ForEach-Object { Write-Host "    $_" -ForegroundColor DarkGray }
            } else {
                Write-Warning "✗ Validation report not found: $validationFile"
            }
        } else {
            Write-Warning "Skipping validation for tool families (use single tool for validation)"
        }
    } else {
        Write-Warning "Skipped validation (use without -SkipValidation to validate)"
    }

    Write-Host ""
    Write-Divider
    Write-Success "Test completed successfully"
    Write-Info "Completed: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
    Write-Divider
    Write-Host ""
    
    # Cleanup temp directory
    Remove-TempDir $tempDir

} catch {
    Write-Host ""
    Write-Divider
    Write-ErrorMessage "Test failed: $($_.Exception.Message)"
    Write-Divider
    
    # Cleanup temp directory
    Remove-TempDir (Join-Path $PSScriptRoot "temp")
    
    exit 1
}
