#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Tool generation and AI improvements orchestration script - runs 2 generators in sequence
    
.DESCRIPTION
    This script orchestrates the tool generation and AI improvements process:
    1. ToolGeneration_Composed - Replaces placeholders with actual content from annotations/parameters/examples
    2. ToolGeneration_Improved - Applies AI-based improvements
    
    Prerequisites:
    - Raw tool files must exist (generated by scripts/Generate-RawTools.ps1)
    - CLI output must exist (./generated/cli/cli-output.json)
    - Annotations, parameters, and example prompts must be generated
    - Azure OpenAI credentials must be configured (for step 2)
    
.PARAMETER OutputPath
    Path to the generated directory (default: ../generated from script location)
    
.PARAMETER SkipComposed
    Skip ToolGeneration_Composed (use existing composed files)
    
.PARAMETER SkipImproved
    Skip ToolGeneration_Improved (skip AI improvements)
    
.PARAMETER MaxTokens
    Maximum tokens for AI improvements (default: 8000)
    
.EXAMPLE
    ./2-Generate-ToolGenerationAndAIImprovements.ps1
    ./2-Generate-ToolGenerationAndAIImprovements.ps1 -SkipImproved
    ./2-Generate-ToolGenerationAndAIImprovements.ps1 -MaxTokens 12000
#>

param(
    [string]$OutputPath = "../generated",
    [switch]$SkipComposed = $false,
    [switch]$SkipImproved = $false,
    [int]$MaxTokens = 8000
)

# Resolve output directory
$generatedDir = if ([System.IO.Path]::IsPathRooted($OutputPath)) {
    $OutputPath
} else {
    $absPath = Join-Path (Get-Location) $OutputPath
    [System.IO.Path]::GetFullPath($absPath)
}

# Get the docs-generation directory
$docsGenDir = $PSScriptRoot

# Resolve output path
$currentDir = Get-Location
if ([System.IO.Path]::IsPathRooted($OutputPath)) {
    $outputDir = $OutputPath
} else {
    $outputDir = Join-Path $currentDir $OutputPath
}

# Normalize to absolute path
$resolvedOutput = Resolve-Path $outputDir -ErrorAction SilentlyContinue
if ($resolvedOutput) {
    $outputDir = $resolvedOutput.ProviderPath
}

# Ensure output directory exists
if (-not (Test-Path $outputDir)) {
    New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
}

# Set up logging
$logDir = Join-Path $outputDir "logs"
if (-not (Test-Path $logDir)) {
    New-Item -ItemType Directory -Path $logDir -Force | Out-Null
}
$logFile = Join-Path $logDir "tool-generation-$(Get-Date -Format 'yyyyMMdd-HHmmss').log"
Start-Transcript -Path $logFile -Append

# Helper functions for colored output
function Write-Info { param([string]$Message) Write-Host "INFO: $Message" -ForegroundColor Cyan }
function Write-Success { param([string]$Message) Write-Host "SUCCESS: $Message" -ForegroundColor Green }
function Write-Warning { param([string]$Message) Write-Host "WARNING: $Message" -ForegroundColor Yellow }
function Write-Error { param([string]$Message) Write-Host "ERROR: $Message" -ForegroundColor Red }
function Write-Progress { param([string]$Message) Write-Host "PROGRESS: $Message" -ForegroundColor Magenta }
function Write-Section { 
    param([string]$Title) 
    Write-Host ""
    Write-Host "═══════════════════════════════════════════════════════════════════" -ForegroundColor Cyan
    Write-Host "  $Title" -ForegroundColor Cyan
    Write-Host "═══════════════════════════════════════════════════════════════════" -ForegroundColor Cyan
    Write-Host ""
}

# Display header
Write-Host ""
Write-Host "╔═══════════════════════════════════════════════════════════════════╗" -ForegroundColor Green
Write-Host "║    Tool Generation and AI Improvements Script                    ║" -ForegroundColor Green
Write-Host "╚═══════════════════════════════════════════════════════════════════╝" -ForegroundColor Green
Write-Host ""
Write-Host "Output Directory: $outputDir" -ForegroundColor White
Write-Host "Log File: $logFile" -ForegroundColor White
Write-Host ""

# Define paths
$cliOutputFile = Join-Path $outputDir "cli/cli-output.json"
$rawToolsDir = Join-Path $outputDir "tools-raw"
$composedToolsDir = Join-Path $outputDir "tools-composed"
$improvedToolsDir = Join-Path $outputDir "tools-ai-improved"
$annotationsDir = Join-Path $outputDir "multi-page/annotations"
$parametersDir = Join-Path $outputDir "multi-page/parameters"
$examplePromptsDir = Join-Path $outputDir "multi-page/example-prompts"

Write-Info "Looking for content in:"
Write-Info "  Annotations:     $annotationsDir"
Write-Info "  Parameters:      $parametersDir"
Write-Info "  Example Prompts: $examplePromptsDir"

# Read MCP CLI version
$mcpCliVersion = "unknown"
$versionFile = Join-Path $outputDir "cli/cli-version.json"
if (Test-Path $versionFile) {
    try {
        $versionContent = Get-Content $versionFile -Raw
        if ($versionContent.Trim().StartsWith('{')) {
            $versionJson = $versionContent | ConvertFrom-Json
            $mcpCliVersion = $versionJson.Version ?? $versionJson.version ?? "unknown"
        } else {
            $mcpCliVersion = $versionContent.Trim()
        }
        Write-Info "MCP CLI Version: $mcpCliVersion"
    }
    catch {
        Write-Warning "Could not read MCP CLI version: $_"
    }
}

# Validate prerequisites
Write-Section "Validating Prerequisites"

$hasErrors = $false

if (-not (Test-Path $cliOutputFile)) {
    Write-Error "CLI output file not found: $cliOutputFile"
    $hasErrors = $true
}
else {
    Write-Success "CLI output file exists"
}

if (-not $SkipComposed) {
    if (-not (Test-Path $annotationsDir)) {
        Write-Warning "Annotations directory not found: $annotationsDir"
    }
    else {
        $annotationCount = (Get-ChildItem $annotationsDir -Filter "*.md" -File).Count
        Write-Success "Annotations directory exists ($annotationCount files)"
    }

    if (-not (Test-Path $parametersDir)) {
        Write-Warning "Parameters directory not found: $parametersDir"
    }
    else {
        $paramCount = (Get-ChildItem $parametersDir -Filter "*.md" -File).Count
        Write-Success "Parameters directory exists ($paramCount files)"
    }

    if (-not (Test-Path $examplePromptsDir)) {
        Write-Warning "Example prompts directory not found: $examplePromptsDir"
    }
    else {
        $promptCount = (Get-ChildItem $examplePromptsDir -Filter "*.md" -File).Count
        Write-Success "Example prompts directory exists ($promptCount files)"
    }
}

if ($hasErrors) {
    Write-Error "Prerequisites validation failed. Exiting."
    Stop-Transcript
    exit 1
}

# Phase 1: Check for Raw Tool Files (generated by scripts/Generate-RawTools.ps1)
Write-Section "Phase 1: Verifying Raw Tool Files"

if (Test-Path $rawToolsDir) {
    $rawCount = (Get-ChildItem $rawToolsDir -Filter "*.md" -File -ErrorAction SilentlyContinue).Count
    if ($rawCount -gt 0) {
        Write-Success "✓ Raw tool files already exist ($rawCount files)"
    } else {
        Write-Error "Raw tool files directory exists but is empty: $rawToolsDir"
        Write-Error "Run scripts/Generate-RawTools.ps1 first"
        Stop-Transcript
        exit 1
    }
} else {
    Write-Error "Raw tool files not found: $rawToolsDir"
    Write-Error "Run scripts/Generate-RawTools.ps1 first"
    Stop-Transcript
    exit 1
}

# Phase 2: ToolGeneration_Composed
if (-not $SkipComposed) {
    Write-Section "Phase 2: Generating Composed Tool Files"
    
    Write-Progress "Running ToolGeneration_Composed..."
    Push-Location $docsGenDir
    
    try {
        $composedArgs = @(
            "--project", "ToolGeneration_Composed",
            "--", 
            $cliOutputFile,
            $rawToolsDir,
            $composedToolsDir,
            $annotationsDir,
            $parametersDir,
            $examplePromptsDir,
            $mcpCliVersion
        )
        
        Write-Info "Command: dotnet run $($composedArgs -join ' ')"
        dotnet run @composedArgs
        
        if ($LASTEXITCODE -ne 0) {
            throw "ToolGeneration_Composed failed with exit code $LASTEXITCODE"
        }
        
        $composedCount = (Get-ChildItem $composedToolsDir -Filter "*.md" -File -ErrorAction SilentlyContinue).Count
        Write-Success "Phase 2 completed - Generated $composedCount composed tool files"
    }
    catch {
        Write-Error "Phase 2 failed: $_"
        Pop-Location
        Stop-Transcript
        exit 1
    }
    finally {
        Pop-Location
    }
}
else {
    Write-Warning "Skipping Phase 2 (ToolGeneration_Composed) - using existing files"
}

# Phase 3: ToolGeneration_Improved
if (-not $SkipImproved) {
    Write-Section "Phase 3: Generating AI-Improved Tool Files"
    
    Write-Progress "Running ToolGeneration_Improved..."
    Push-Location $docsGenDir
    
    try {
        $improvedArgs = @(
            "--project", "ToolGeneration_Improved",
            "--", 
            $cliOutputFile,
            $composedToolsDir,
            $improvedToolsDir,
            $mcpCliVersion,
            $MaxTokens
        )
        
        Write-Info "Command: dotnet run $($improvedArgs -join ' ')"
        dotnet run @improvedArgs
        
        if ($LASTEXITCODE -ne 0) {
            throw "ToolGeneration_Improved failed with exit code $LASTEXITCODE"
        }
        
        $improvedCount = (Get-ChildItem $improvedToolsDir -Filter "*.md" -File -ErrorAction SilentlyContinue).Count
        Write-Success "Phase 3 completed - Generated $improvedCount improved tool files"
    }
    catch {
        Write-Error "Phase 3 failed: $_"
        Pop-Location
        Stop-Transcript
        exit 1
    }
    finally {
        Pop-Location
    }
}
else {
    Write-Warning "Skipping Phase 3 (ToolGeneration_Improved) - AI improvements disabled"
}

# Summary
Write-Section "Generation Summary"

$rawCount = if (Test-Path $rawToolsDir) { (Get-ChildItem $rawToolsDir -Filter "*.md" -File -ErrorAction SilentlyContinue).Count } else { 0 }
$composedCount = if (Test-Path $composedToolsDir) { (Get-ChildItem $composedToolsDir -Filter "*.md" -File -ErrorAction SilentlyContinue).Count } else { 0 }
$improvedCount = if (Test-Path $improvedToolsDir) { (Get-ChildItem $improvedToolsDir -Filter "*.md" -File -ErrorAction SilentlyContinue).Count } else { 0 }

Write-Host "  Raw tool files:      $rawCount" -ForegroundColor White
Write-Host "  Composed tool files: $composedCount" -ForegroundColor White
Write-Host "  Improved tool files: $improvedCount" -ForegroundColor White
Write-Host ""

Write-Success "All phases completed successfully!"
Write-Info "Log file: $logFile"
Stop-Transcript
