// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using ToolFamilyCleanup.Services;
using Xunit;

namespace DocGeneration.Steps.ToolFamilyCleanup.Tests;

/// <summary>
/// Tests for ScaffoldingCommentStripper to ensure HTML scaffolding comments
/// are removed while preserving <!-- @mcpcli --> tool markers.
/// </summary>
public class ScaffoldingCommentStripperTests
{
    // ── Core stripping behavior ─────────────────────────────────────

    [Fact]
    public void Strip_RemovesRequiredParametersComment()
    {
        var content = @"Description of the tool.

<!-- Required parameters: 3 - 'app', 'resource-group', 'database' -->

Example prompts include:

- ""List all web apps.""";

        var result = ScaffoldingCommentStripper.Strip(content);

        Assert.DoesNotContain("<!-- Required parameters:", result);
        Assert.Contains("Example prompts include:", result);
        Assert.Contains("\"List all web apps.\"", result);
    }

    [Fact]
    public void Strip_PreservesMcpCliMarkers()
    {
        var content = @"## deploy plan get

<!-- @mcpcli deploy plan get -->

Description of the tool.";

        var result = ScaffoldingCommentStripper.Strip(content);

        Assert.Contains("<!-- @mcpcli deploy plan get -->", result);
        Assert.Contains("Description of the tool.", result);
    }

    [Fact]
    public void Strip_RemovesMultipleScaffoldingComments()
    {
        var content = @"## Tool 1

<!-- Required parameters: 2 - 'param1', 'param2' -->

Description for tool 1.

## Tool 2

<!-- Required parameters: 0 -  -->

Description for tool 2.

## Tool 3

<!-- Generated by step 3 -->

Description for tool 3.";

        var result = ScaffoldingCommentStripper.Strip(content);

        Assert.DoesNotContain("<!-- Required parameters:", result);
        Assert.DoesNotContain("<!-- Generated by step 3 -->", result);
        Assert.Contains("Description for tool 1.", result);
        Assert.Contains("Description for tool 2.", result);
        Assert.Contains("Description for tool 3.", result);
    }

    [Fact]
    public void Strip_NoComments_ReturnsUnchanged()
    {
        var content = @"## Tool 1

Description of the tool.

Example prompts include:

- ""List all items.""";

        var result = ScaffoldingCommentStripper.Strip(content);

        Assert.Equal(content, result);
    }

    [Fact]
    public void Strip_MixedComments_OnlyStripsScaffolding()
    {
        var content = @"## deploy plan get

<!-- @mcpcli deploy plan get -->

Description of the tool.

<!-- Required parameters: 3 - 'app', 'resource-group', 'database' -->

Example prompts include:

- ""Deploy my app.""

## deploy plan list

<!-- @mcpcli deploy plan list -->

<!-- Required parameters: 0 -  -->

List all plans.";

        var result = ScaffoldingCommentStripper.Strip(content);

        // @mcpcli markers preserved
        Assert.Contains("<!-- @mcpcli deploy plan get -->", result);
        Assert.Contains("<!-- @mcpcli deploy plan list -->", result);
        // Scaffolding removed
        Assert.DoesNotContain("<!-- Required parameters:", result);
        // Content preserved
        Assert.Contains("Description of the tool.", result);
        Assert.Contains("List all plans.", result);
    }

    [Fact]
    public void Strip_NullOrEmpty_ReturnsInput()
    {
        Assert.Equal("", ScaffoldingCommentStripper.Strip(""));
        Assert.Null(ScaffoldingCommentStripper.Strip(null!));
    }

    [Fact]
    public void Strip_MultilineComment_IsStripped()
    {
        var content = @"## Tool

<!-- Required parameters: 2 -
  'subscription',
  'resource-group' -->

Description.";

        var result = ScaffoldingCommentStripper.Strip(content);

        Assert.DoesNotContain("<!-- Required parameters:", result);
        Assert.DoesNotContain("subscription", result);
        Assert.Contains("Description.", result);
    }

    [Fact]
    public void Strip_ZeroRequiredParameters_IsStripped()
    {
        var content = @"[Tool annotation hints](index.md#tool-annotations):
Destructive: no

<!-- Required parameters: 0 -  -->

Example prompts include:

- ""List all accounts.""";

        var result = ScaffoldingCommentStripper.Strip(content);

        Assert.DoesNotContain("<!-- Required parameters:", result);
        Assert.Contains("Example prompts include:", result);
    }

    [Fact]
    public void Strip_GenericScaffoldingComment_IsStripped()
    {
        var content = @"## Tool

<!-- This section was auto-generated -->

Description of the tool.";

        var result = ScaffoldingCommentStripper.Strip(content);

        Assert.DoesNotContain("<!-- This section was auto-generated -->", result);
        Assert.Contains("Description of the tool.", result);
    }

    [Fact]
    public void Strip_CleansUpExcessiveBlankLines()
    {
        var content = "## Tool\n\n<!-- Required parameters: 1 - 'name' -->\n\nDescription.";

        var result = ScaffoldingCommentStripper.Strip(content);

        // Should not have 3+ consecutive newlines
        Assert.DoesNotContain("\n\n\n", result);
        Assert.Contains("## Tool", result);
        Assert.Contains("Description.", result);
    }
}
