#!/bin/bash
# Demo script to show the namespace-specific output directory feature
# This demonstrates how the output directory changes based on the namespace parameter

set -euo pipefail

echo "=================================================================="
echo "Demo: Namespace-Specific Output Directory Feature"
echo "=================================================================="
echo ""
echo "This feature changes the output directory based on usage:"
echo ""
echo "1. When running for ALL namespaces:"
echo "   Command: ./start.sh"
echo "   Output:  ./generated/"
echo ""
echo "2. When running for a SPECIFIC namespace:"
echo "   Command: ./start.sh advisor"
echo "   Output:  ./generated-advisor/"
echo ""
echo "3. When running specific steps for a namespace:"
echo "   Command: ./start.sh advisor 1,2,3"
echo "   Output:  ./generated-advisor/"
echo ""
echo "=================================================================="
echo "Benefits:"
echo "=================================================================="
echo ""
echo "✓ Work on a single service without affecting the full catalog"
echo "✓ Keep generated docs isolated per namespace during development"
echo "✓ Easy to identify which namespace generated which output"
echo "✓ Prevents accidental overwrites when working on specific services"
echo ""
echo "=================================================================="
echo "Examples:"
echo "=================================================================="
echo ""
echo "# Generate only advisor namespace documentation:"
echo "  ./start.sh advisor 1"
echo "  → Output: ./generated-advisor/tool-family/advisor.md"
echo ""
echo "# Generate storage namespace with AI enhancements:"
echo "  ./start.sh storage 1,2,3"
echo "  → Output: ./generated-storage/tool-family/storage.md"
echo ""
echo "# Generate full catalog:"
echo "  ./start.sh"
echo "  → Output: ./generated/tool-family/*.md (all 52 namespaces)"
echo ""
echo "=================================================================="
